name: Django CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]

    # 내가 추가한 코드블록(just to avoid any errors after migrating database)
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_DB: mysite_db
          POSTGRES_USER: mysite_user
          POSTGRES_PASSWORD: mysite_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: mysite_db
      DB_USER: mysite_user
      DB_PASSWORD: mysite_password
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: |
          python manage.py migrate --noinput
      - name: Debug Info
        run: |
          python manage.py showmigrations todo
          python manage.py shell -c "from django.conf import settings; print('DATABASES =', settings.DATABASES)"
      - name: Run Tests
        run: |
          python manage.py test --verbosity 2
